### PR TITLE
The

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**
If this is the *one* non-type I'd need to import, then maybe this kinda works. This probably doesn't belong here and I'm sure everyone else hates the name. I'm willing to compromise on either point.

### CODE REVIEW

**Comment by SamPruden** [comment]
I'm merging these for now as they're useful for you and the full replacement system will take longer than I'd hoped, the compiler doesn't quite expose everything I need yet. These are (hopefully) temporary, but they're in for now.

**Comment by KiaraGrouwstra** [comment]
Thank you!
What are the issues you're running into with the compiler? I wonder if I might be able to think along there.

**Comment by SamPruden** [comment]
As far as I can tell, the compiler doesn't actually expose the type comparison methods I need to be able to do the transform-time assertions. Mainly that would only be `.is<T>()` for now. I'm going to put together a version that does the best it can with what we've got available, but it won't be feature complete or a stable API yet.

The compiler has an internal method `isTypeRelatedTo` that can do everything this needs, it just needs to be exposed. It's actually a very simple change so I may put a PR in for it and see if I can get that through, I just need to check if I'd be expected to do a daunting amount of grokking/writing tests for that.

**Comment by KiaraGrouwstra** [comment]
Seems worth finding out! 😃

**Pull request merged**
